services:
  db:
    environment:
      - POSTGRES_PASSWORD=password
      #- POSTGRES_HOST_AUTH_METHOD=trust
      - DATABASE_URL=postgresql://localhost:5432/wordcount_dev
    image: "postgres:15"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  dbdata:
