services:
  db:
    environment:
      - POSTGRES_PASSWORD=password
      #- POSTGRES_HOST_AUTH_METHOD=trust
    image: "postgres:15"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
